project_name: "Bitcoin_RL_Trader"
model_type: "DQN"
seed: 42
leverage: 10
max_capital_usage: 0.02
symbol: "BTCUSDT"
timeframes: "1h"

system:
  device: "cpu"
  n_envs: 4

paths:
  data_full: "../data/processed/BTCUSDT_1h_features_full.csv"
  data_state: "../data/processed/BTCUSDT_1h_state.csv"
  models_dir: "../model"
  ppo_dir: "../model/PPO_1h_Bitcoin_RL_Trader/final_model.zip"
  dqn_dir: "../model/DQN_1h_Bitcoin_RL_Trader/final_model.zip"
  logs_dir: "../tensorboard_logs"

env:
  initial_balance: 10000
  fee_rate: 0.0004
  window_size: 90
  max_episode_steps: 500

reward:
  15m:
    scaling: 15.0
    alpha: 1.5
    beta: 0.12
    holding_penalty: 0.0003
    dd_threshold: 0.05
    clip_low: -1.5
    clip_high: 1.5
    stop_loss_pct: 0.008
    noise_threshold: 0.001

  5m:
    scaling: 500.0
    alpha: 15.0
    beta: 0.05
    holding_penalty: 0.00001
    flat_penalty: 0.00001
    fee_penalty_factor: 2.0
    active_bonus_rate: 0.0
    fee_rate_hold_per_12h: 0.0001
    holding_fee_period: 144
    dd_threshold: 0.05
    clip_low: -5.0
    clip_high: 5.0
    stop_loss_pct: 0.008
    liquidation_penalty: -10.0

  1h:
    transaction_cost: 0.0002
    scaling: 150.0
    clip_low: -1.5
    clip_high: 1.5
    funding_rate: 0.0001
    funding_period: 8
    short_bonus_when_longtrend: 0.00002
    terminal_loss_threshold: 0.30
    terminal_loss_penalty: -0.5
    terminal_profit_multiplier: 0.5
    terminal_loss_multiplier: -0.2

ppo_params:
  policy: "MlpPolicy"
  learning_rate: 0.0001
  n_steps: 2048
  batch_size: 256
  n_epochs: 5
  gamma: 0.97
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  verbose: 1

dqn_params:
  fixed_qty: 0.05
  policy: "MlpPolicy"
  learning_rate: 0.0001
  buffer_size: 100000
  learning_starts: 1000
  batch_size: 128
  tau: 1.0
  gamma: 0.97
  train_freq: 4
  gradient_steps: 1
  target_update_interval: 2000
  exploration_fraction: 0.1
  exploration_final_eps: 0.05
  verbose: 1

training:
  total_timesteps: 500000
  save_interval: 50000